name: BdsCore
file: Dockerfile
tag: bdsmaneger/core:dev
target: bdscore
buildx:
  enable: true
  platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

# Docker Run envs
env:
  - name: TELEGRAM_TOKEN
    value: null
  
  - name: DESCRIPTION
    value: Docker Test
  
  - name: WORLD_NAME
    value: Docker Run Test
  
  - name: GAMEMODE
    value: survival
  
  - name: DIFFICULTY
    value: normal
  
  - name: XBOX_ACCOUNT
    value: false
  
  - name: PLAYERS
    value: 8
  
  - name: BDS_VERSION
    value: latest

  - name: SERVER
    value: bedrock

# Docker Run Mount
mount:
  - path: /home/bds/bds_core/
    from: ${HOME}/bds_core/

# Docker Run Ports
ports:
  - port: 19132
    external: 19132
    protocoll: udp

  - port: 80
    external: 8880
    protocoll: tcp

# More options
options:
  build: []
    # - "--platforms=linux/amd64"
  run:
    - "--net=host"
  runArgv: []
