name: Bds Maneger - Docker Base
on:
  push:
    tags:
      - v*
      - V*

#  schedule:
#    - cron: 0 0 * * */6

env:
  DOCKER_ARCHS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_ORG_USER }}
          password: ${{ secrets.DOCKER_ORG_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: bdsbase
          tags: |
            bdsmaneger/node_image:latest
            bdsmaneger/node_image:${{ github.run_id }}
          platforms: ${{ env.DOCKER_ARCHS }}
